# This file lints out view files that end in *.haml
linters:
  LineLength:
    max: 120
    severity: error
  Indentation: # For consistency with default rubocop rules.
    character: space
    width: 2
    severity: error
  SpaceInsideHashAttributes:
    enabled: false

exclude:
  - "node_modules/**/*"
  - "vendor/**/*"
